const ROLES = {
  ADMIN: 'ADMIN',
  HR_MANAGER: 'HR_MANAGER',
  HR_PAYROLL_MANAGER: 'HR_PAYROLL_MANAGER',
  HR_PAYROLL_USER: 'HR_PAYROLL_USER',
  EMPLOYEE: 'EMPLOYEE',
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: {
    canManageEmployees: true,
    canManageAttendance: true,
    canManageContracts: true,
    canManageSchedules: true,
    canManageTimeOff: true,
    canApproveTimeOff: true,
    canAccessPayroll: true,
    canManagePayroll: true,
    canComputePayrun: true,
    canValidatePayrun: true,
    canManageUsers: true,
    canManageSystem: true,
    canViewOwnProfile: true,
    canViewOwnAttendance: true,
    canCreateOwnAttendance: true,
    canViewOwnLeaveBalances: true,
    canCreateOwnTimeOffRequests: true,
  },
  [ROLES.HR_PAYROLL_MANAGER]: {
    canManageEmployees: true,
    canManageAttendance: true,
    canManageContracts: true,
    canManageSchedules: true,
    canManageTimeOff: true,
    canApproveTimeOff: true,
    canAccessPayroll: true,
    canManagePayroll: true,
    canComputePayrun: true,
    canValidatePayrun: true,
    canManageUsers: false,
    canManageSystem: false,
    canViewOwnProfile: true,
    canViewOwnAttendance: true,
    canCreateOwnAttendance: true,
    canViewOwnLeaveBalances: true,
    canCreateOwnTimeOffRequests: true,
  },
  [ROLES.HR_MANAGER]: {
    canManageEmployees: true,
    canManageAttendance: true,
    canManageContracts: true,
    canManageSchedules: true,
    canManageTimeOff: true,
    canApproveTimeOff: true,
    canAccessPayroll: false,
    canManagePayroll: false,
    canComputePayrun: false,
    canValidatePayrun: false,
    canManageUsers: false,
    canManageSystem: false,
    canViewOwnProfile: true,
    canViewOwnAttendance: true,
    canCreateOwnAttendance: true,
    canViewOwnLeaveBalances: true,
    canCreateOwnTimeOffRequests: true,
  },
  [ROLES.HR_PAYROLL_USER]: {
    canManageEmployees: false,
    canManageAttendance: false,
    canManageContracts: false,
    canManageSchedules: false,
    canManageTimeOff: false,
    canApproveTimeOff: false,
    canAccessPayroll: true,
    canManagePayroll: false,
    canComputePayrun: true,
    canValidatePayrun: false,
    canManageUsers: false,
    canManageSystem: false,
    canViewOwnProfile: true,
    canViewOwnAttendance: true,
    canCreateOwnAttendance: true,
    canViewOwnLeaveBalances: true,
    canCreateOwnTimeOffRequests: true,
  },
  [ROLES.EMPLOYEE]: {
    canManageEmployees: false,
    canManageAttendance: false,
    canManageContracts: false,
    canManageSchedules: false,
    canManageTimeOff: false,
    canApproveTimeOff: false,
    canAccessPayroll: false,
    canManagePayroll: false,
    canComputePayrun: false,
    canValidatePayrun: false,
    canManageUsers: false,
    canManageSystem: false,
    canViewOwnProfile: true,
    canViewOwnAttendance: true,
    canCreateOwnAttendance: true,
    canViewOwnLeaveBalances: true,
    canCreateOwnTimeOffRequests: true,
  },
};

const getPermissionsForRole = (role) => ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS[ROLES.EMPLOYEE];

module.exports = {
  ROLES,
  ROLE_PERMISSIONS,
  getPermissionsForRole,
};
